src/Entity/Formation.php
<?php

namespace App\Entity;

use Symfony\Component\Uid\Uuid;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\FormationRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Ignore;

#[ORM\Entity(repositoryClass: FormationRepository::class)]
class Formation
{
  #[ORM\Id]
  #[ORM\Column(type: UuidType::NAME, unique: true)]
  #[ORM\GeneratedValue(strategy: 'CUSTOM')]
  #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
  private ?Uuid $id = null;

  #[ORM\Column(length: 255)]
  #[Assert\NotBlank]
  #[Assert\Length(
    max: 255,
    maxMessage: 'Le nom ne peut pas contenir plus de 255 caractères.',
  )]
  private ?string $name = null;

  #[ORM\Column]
  #[Assert\NotBlank]
  #[Assert\PositiveOrZero]
  private ?int $studies_level = null;

  #[Ignore]
  #[ORM\ManyToMany(targetEntity: Code::class, inversedBy: 'formations')]
  private Collection $codes;

  #[Ignore]
  #[ORM\ManyToMany(targetEntity: Job::class, inversedBy: 'formations')]
  private Collection $jobs;

  #[Ignore]
  #[ORM\ManyToMany(targetEntity: Condition::class, inversedBy: 'formations')]
  private Collection $conditions;

  #[Ignore]
  #[ORM\ManyToMany(targetEntity: Cost::class, inversedBy: 'formations')]
  private Collection $costs;

  #[Ignore]
  #[ORM\ManyToMany(targetEntity: Location::class, inversedBy: 'formations')]
  private Collection $locations;

  #[Ignore]
  #[ORM\ManyToMany(targetEntity: self::class)]
  private Collection $sequels;

  #[ORM\Column]
  #[Assert\NotBlank]
  #[Assert\Positive]
  private ?int $duration = null;

  #[Ignore]
  #[ORM\ManyToMany(targetEntity: Format::class, inversedBy: 'formations')]
  private Collection $formats;

  #[ORM\Column(length: 255)]
  #[Assert\NotBlank]
  #[Assert\Length(
    max: 255,
    maxMessage: 'La description ne peut pas contenir plus de 255 caractères.',
  )]
  private ?string $descriptive = null;

  #[ORM\Column]
  private ?bool $state = null;

  #[ORM\Column(nullable: true)]
  private ?int $duration_entreprise = null;

  #[ORM\Column(length: 255, nullable: true)]
  private ?string $results = null;

  #[ORM\Column(length: 255, nullable: true)]
  private ?string $certifications = null;

  public function __construct()
  {
    $this->codes = new ArrayCollection();
    $this->jobs = new ArrayCollection();
    $this->conditions = new ArrayCollection();
    $this->costs = new ArrayCollection();
    $this->locations = new ArrayCollection();
    $this->sequels = new ArrayCollection();
    $this->formats = new ArrayCollection();
  }

  public function __toString(): string
  {
    return $this->name;
  }

  public function getId(): ?Uuid
  {
    return $this->id;
  }

  public function getName(): ?string
  {
    return $this->name;
  }

  public function setName(string $name): self
  {
    $this->name = $name;

    return $this;
  }

  public function getStudiesLevel(): ?int
  {
    return $this->studies_level;
  }

  public function setStudiesLevel(int $studies_level): self
  {
    $this->studies_level = $studies_level;

    return $this;
  }

  /**
   * @return Collection<int, Code>
   */
  public function getCodes(): Collection
  {
    return $this->codes;
  }

  public function addCode(Code $code): self
  {
    if (!$this->codes->contains($code))
    {
      $this->codes->add($code);
    }

    return $this;
  }

  public function removeCode(Code $code): self
  {
    $this->codes->removeElement($code);

    return $this;
  }

  /**
   * @return Collection<int, Job>
   */
  public function getJobs(): Collection
  {
    return $this->jobs;
  }

  public function addJob(Job $job): self
  {
    if (!$this->jobs->contains($job))
    {
      $this->jobs->add($job);
    }

    return $this;
  }

  public function removeJob(Job $job): self
  {
    $this->jobs->removeElement($job);

    return $this;
  }

  /**
   * @return Collection<int, Condition>
   */
  public function getConditions(): Collection
  {
    return $this->conditions;
  }

  public function addCondition(Condition $condition): self
  {
    if (!$this->conditions->contains($condition))
    {
      $this->conditions->add($condition);
    }

    return $this;
  }

  public function removeCondition(Condition $condition): self
  {
    $this->conditions->removeElement($condition);

    return $this;
  }

  /**
   * @return Collection<int, Cost>
   */
  public function getCosts(): Collection
  {
    return $this->costs;
  }

  public function addCost(Cost $cost): self
  {
    if (!$this->costs->contains($cost))
    {
      $this->costs->add($cost);
    }

    return $this;
  }

  public function removeCost(Cost $cost): self
  {
    $this->costs->removeElement($cost);

    return $this;
  }

  /**
   * @return Collection<int, Location>
   */
  public function getLocations(): Collection
  {
    return $this->locations;
  }

  public function addLocation(Location $location): self
  {
    if (!$this->locations->contains($location))
    {
      $this->locations->add($location);
    }

    return $this;
  }

  public function removeLocation(Location $location): self
  {
    $this->locations->removeElement($location);

    return $this;
  }

  /**
   * @return Collection<int, self>
   */
  public function getSequels(): Collection
  {
    return $this->sequels;
  }

  public function addSequel(self$sequel): self
  {
    if (!$this->sequels->contains($sequel))
    {
      $this->sequels->add($sequel);
    }

    return $this;
  }

  public function removeSequel(self$sequel): self
  {
    $this->sequels->removeElement($sequel);

    return $this;
  }

  public function getDuration(): ?int
  {
    return $this->duration;
  }

  public function setDuration(int $duration): self
  {
    $this->duration = $duration;

    return $this;
  }

  /**
   * @return Collection<int, Format>
   */
  public function getFormats(): Collection
  {
    return $this->formats;
  }

  public function addFormat(Format $format): self
  {
    if (!$this->formats->contains($format))
    {
      $this->formats->add($format);
    }

    return $this;
  }

  public function removeFormat(Format $format): self
  {
    $this->formats->removeElement($format);

    return $this;
  }

  public function getDescriptive(): ?string
  {
      return $this->descriptive;
  }

  public function setDescriptive(string $descriptive): self
  {
      $this->descriptive = $descriptive;

      return $this;
  }

  public function isState(): ?bool
  {
      return $this->state;
  }

  public function setState(bool $state): self
  {
      $this->state = $state;

      return $this;
  }

  public function getDurationEntreprise(): ?int
  {
      return $this->duration_entreprise;
  }

  public function setDurationEntreprise(?int $duration_entreprise): self
  {
      $this->duration_entreprise = $duration_entreprise;

      return $this;
  }

  public function getResults(): ?string
  {
      return $this->results;
  }

  public function setResults(?string $results): self
  {
      $this->results = $results;

      return $this;
  }

  public function getCertifications(): ?string
  {
      return $this->certifications;
  }

  public function setCertifications(?string $certifications): self
  {
      $this->certifications = $certifications;

      return $this;
  }
}

src/Controller/FormationTypeController.php
<?php

namespace App\Controller;

use App\Entity\Formation;
use App\Form\FormationType;
use App\Repository\FormationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/backoffice/formation/type')]
class FormationTypeController extends AbstractController
{


    /**
     * Récupération Toutes les formations
     */
    #[Route('/', name: 'app_formation_type_index', methods: ['GET'])]
    public function index(FormationRepository $formationRepository): Response
    {   
        $tmp = $formationRepository->findAll();
        return $this->render('formation_type/index.html.twig', [
            'formations' => $tmp,
        ]);
    }

    #[Route('/new', name: 'app_formation_type_new', methods: ['GET', 'POST'])]
    public function new(Request $request, FormationRepository $formationRepository): Response
    {
        $formation = new Formation();
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $formationRepository->save($formation, true);

            return $this->redirectToRoute('app_formation_type_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('formation_type/new.html.twig', [
            'formation' => $formation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_formation_type_show', methods: ['GET'])]
    public function show(Formation $formation): Response
    {
        return $this->render('formation_type/show.html.twig', [
            'formation' => $formation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_formation_type_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Formation $formation, FormationRepository $formationRepository): Response
    {
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $formationRepository->save($formation, true);

            return $this->redirectToRoute('app_formation_type_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('formation_type/edit.html.twig', [
            'formation' => $formation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_formation_type_delete', methods: ['POST'])]
    public function delete(Request $request, Formation $formation, FormationRepository $formationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$formation->getId(), $request->request->get('_token'))) {
            $formationRepository->remove($formation, true);
        }

        return $this->redirectToRoute('app_formation_type_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/formation_type/_delete_form.html.twig
<form method="post" action="{{ path('app_formation_type_delete', {'id': formation.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer cette formation ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formation.id) }}">
    <button class="btn mt-2"><img src="{{asset('build/img/trash-icon.svg')}}" alt="icon poubelle" title="Supprimer"></button>
</form>

templates/formation_type/_form.html.twig
{{ form_start(form) }}
{% form_theme form 'bootstrap_5_layout.html.twig' %}

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.name, "Nom de la formation :") }}
            {{ form_widget(form.name) }}
            {{ form_errors(form.name) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.studies_level, "Niveau d'étude :") }}
            {{ form_widget(form.studies_level) }}
            {{ form_errors(form.studies_level) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.descriptive, "Description :") }}
            {{ form_widget(form.descriptive) }}
            {{ form_errors(form.descriptive) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.duration, 'Durée :') }}
            {{ form_widget(form.duration) }}
            {{ form_errors(form.duration) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.duration_entreprise, 'Durée en entreprise:') }}
            {{ form_widget(form.duration_entreprise) }}
            {{ form_errors(form.duration_entreprise) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.results, 'Résultats:') }}
            {{ form_widget(form.results) }}
            {{ form_errors(form.results) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.certifications, 'Certifications:') }}
            {{ form_widget(form.certifications) }}
            {{ form_errors(form.certifications) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.codes, 'Codes :') }}
            {{ form_widget(form.codes) }}
            {{ form_errors(form.codes) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.jobs, 'Métiers visés :') }}
            {{ form_widget(form.jobs) }}
            {{ form_errors(form.jobs) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.conditions, "Conditions d'admission :") }}
            {{ form_widget(form.conditions) }}
            {{ form_errors(form.conditions) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.costs, "Frais de scolarité :") }}
            {{ form_widget(form.costs) }}
            {{ form_errors(form.costs) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.locations, "Lieux :") }}
            {{ form_widget(form.locations) }}
            {{ form_errors(form.locations) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.formats, "Formats :") }}
            {{ form_widget(form.formats) }}
            {{ form_errors(form.formats) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.sequels, "Suites possibles :") }}
            {{ form_widget(form.sequels) }}
            {{ form_errors(form.sequels) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.state, "État :") }}
            {{ form_widget(form.state) }}
            {{ form_errors(form.state) }}
        </div>   
    </div>

    <div class="row mt-2">
        <div class="col-lg-10 d-flex justify-content-end">
            <button class="btn btn-primary my-3">{{ button_label|default('Sauvegarder') }}</button>
        </div>
    </div>
{{ form_end(form) }}

templates/formation_type/edit.html.twig
{% extends 'backoffice_base.html.twig' %}

{% block title %}Formation | Éditer{% endblock %}

{% block body %}
    <div class="page" data-current="formations"></div>
    <div class="d-flex justify-content-between mb-5 col-lg-10">
        <div class="d-flex">
            <h1>Éditer une formation</h1>
            {{ include('formation_type/_delete_form.html.twig') }}
        </div>
        <div class="d-flex mt-3">
            <a class="me-3" href="{{ path('app_training_details', {'id': formation.id}) }}"><img src="{{asset('build/img/preview-icon.svg')}}" class="mt-1" alt="icon edit" title="Aperçu de l'entité"></a>
            <a href="{{ path('app_formation_type_index') }}"><img src="{{asset('build/img/back-icon.svg')}}" alt="icon back" title="Retour en arrière"></a>
        </div>
    </div>

    
        {{ include('formation_type/_form.html.twig', {'button_label': 'Modifier'}) }}

    <div class="d-flex justify-content-center">
        
    </div>
    

    {% block javascripts %}
        {{ encore_entry_script_tags('backoffice') }}
        {{parent()}}
    {% endblock %}
    
{% endblock %}

templates/formation_type/index.html.twig
{% extends 'backoffice_base.html.twig' %}

{% block title %}Formations | Index{% endblock %}

{% block body %}
    <div class="page" data-current="formations"></div>
    <div class="d-flex justify-content-between mb-5">
        <h1>Formations</h1>
        <a href="{{ path('app_formation_type_new') }}"><img src="{{asset('build/img/plus-icon.svg')}}" alt="icon plus" title="Ajouter une formation"></a>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>État</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for formation in formations %}
            <tr>
                <td>{{ formation.name }}</td>
                <td>
                    {% if formation.state %}
                        En ligne
                    {% else %}
                        Hors ligne
                    {% endif %}
                </td>
                <td>
                    <div class="d-flex justify-content-around">
                        <a href="{{ path('app_formation_type_show', {'id': formation.id}) }}"><img src="{{asset('build/img/show-icon.svg')}}" alt="icon show" title="Voir l'entité"></a>
                        <a href="{{ path('app_formation_type_edit', {'id': formation.id}) }}"><img src="{{asset('build/img/edit-icon.svg')}}" class="mx-2" alt="icon edit" title="Modifier l'entité"></a>
                        <a href="{{ path('app_training_details', {'id': formation.id}) }}"><img src="{{asset('build/img/preview-icon.svg')}}" class="mt-1" alt="icon edit" title="Aperçu de l'entité"></a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% block javascripts %}
        {{ encore_entry_script_tags('backoffice') }}
        {{parent()}}
    {% endblock %}

{% endblock %}

templates/formation_type/new.html.twig
{% extends 'backoffice_base.html.twig' %}

{% block title %}Formation | Nouveau{% endblock %}

{% block body %}
    <div class="page" data-current="formations"></div>
    <div class="d-flex justify-content-between mb-5 col-lg-10">
        <h1>Créer une nouvelle formation</h1>
        <a class="mt-3" href="{{ path('app_formation_type_index') }}"><img src="{{asset('build/img/back-icon.svg')}}" alt="icon back" title="Retour en arrière"></a>
    </div>

    {{ include('formation_type/_form.html.twig') }}

    {% block javascripts %}
        {{ encore_entry_script_tags('backoffice') }}
        {{parent()}}
    {% endblock %}
    
{% endblock %}

templates/formation_type/show.html.twig
{% extends 'backoffice_base.html.twig' %}

{% block title %}Formation | Aperçu{% endblock %}

{% block body %}
    <div class="page" data-current="formations"></div>
    <div class="d-flex justify-content-between mb-5 col-lg-10">
        <div class="d-flex">
            <h1>Formation</h1>
            {{ include('formation_type/_delete_form.html.twig') }}
        </div>
        <div class="d-flex mt-3">
            <a href="{{ path('app_formation_type_edit', {'id': formation.id}) }}"><img src="{{asset('build/img/edit-icon.svg')}}" alt="icon edit" title="Modifier l'entité"></a>
            <a class="mx-3" href="{{ path('app_training_details', {'id': formation.id}) }}"><img src="{{asset('build/img/preview-icon.svg')}}" class="mt-1" alt="icon edit" title="Aperçu de l'entité"></a>
            <a href="{{ path('app_formation_type_index') }}"><img src="{{asset('build/img/back-icon.svg')}}" alt="icon back" title="Retour en arrière"></a>
        </div>
    </div>

    <div class="col-lg-10">
        <table class="table">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ formation.id }}</td>
                </tr>
                <tr>
                    <th>État</th>
                    <td>
                        {% if formation.state %}
                            En ligne
                        {% else %}
                            Hors ligne
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th>Nom</th>
                    <td>{{ formation.name }}</td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>{{ formation.descriptive }}</td>
                </tr>
                <tr>
                    <th>Niveau d'étude</th>
                    <td>{{ formation.studiesLevel }}</td>
                </tr>
                <tr>
                    <th>Durée</th>
                    <td>{{ formation.duration }} heures</td>
                </tr>
                <tr>
                    <th>Codes</th>
                    <td>
                        {% for code in formation.codes %}
                            {{code}}<br/>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>Métiers visés</th>
                    <td>
                        {% for job in formation.jobs %}
                            {{job}}<br/>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>Conditions d'admission</th>
                    <td>
                        {% for condition in formation.conditions %}
                            {{condition}}<br/>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>Frais de scolarité</th>
                    <td>
                        {% for cost in formation.costs %}
                            {{cost}}<br/>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>Lieux</th>
                    <td>
                        {% for location in formation.locations %}
                            {{location}}<br/>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>Format</th>
                    <td>
                        {% for format in formation.formats %}
                            {{format}}<br/>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>Suites possibles</th>
                    <td>
                        {% for sequel in formation.sequels %}
                            {{sequel}}<br/>
                        {% endfor %}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    {% block javascripts %}
        {{ encore_entry_script_tags('backoffice') }}
        {{parent()}}
    {% endblock %}
{% endblock %}