src/Entity/Code.php
<?php

namespace App\Entity;

use Symfony\Component\Uid\Uuid;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CodeRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: CodeRepository::class)]
class Code
{
  #[ORM\Id]
  #[ORM\Column(type: UuidType::NAME, unique: true)]
  #[ORM\GeneratedValue(strategy: 'CUSTOM')]
  #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
  private ?Uuid $id = null;

  #[ORM\Column(length: 255)]
  private ?string $identifier = null;

  #[ORM\Column(length: 255, nullable: true)]
  private ?string $title = null;

  #[ORM\ManyToMany(targetEntity: Formation::class, mappedBy: 'codes')]
  private Collection $formations;

  #[ORM\ManyToMany(targetEntity: Skill::class, inversedBy: 'codes')]
  private Collection $skills;

  #[ORM\Column]
  private ?bool $is_main = null;

  public function __construct()
  {
    $this->formations = new ArrayCollection();
    $this->skills = new ArrayCollection();
  }

  public function __toString(): string
  {
    return $this->identifier;
  }

  public function getId(): ?Uuid
  {
    return $this->id;
  }

  public function getIdentifier(): ?string
  {
    return $this->identifier;
  }

  public function setIdentifier(string $identifier): self
  {
    $this->identifier = $identifier;

    return $this;
  }

  public function getTitle(): ?string
  {
    return $this->title;
  }

  public function setTitle(string $title): self
  {
    $this->title = $title;

    return $this;
  }

  /**
   * @return Collection<int, Formation>
   */
  public function getFormations(): Collection
  {
    return $this->formations;
  }

  public function addFormation(Formation $formation): self
  {
    if (!$this->formations->contains($formation))
    {
      $this->formations->add($formation);
      $formation->addCode($this);
    }

    return $this;
  }

  public function removeFormation(Formation $formation): self
  {
    if ($this->formations->removeElement($formation))
    {
      $formation->removeCode($this);
    }

    return $this;
  }

  /**
   * @return Collection<int, Skill>
   */
  public function getSkills(): Collection
  {
    return $this->skills;
  }

  public function addSkill(Skill $skill): self
  {
    if (!$this->skills->contains($skill))
    {
      $this->skills->add($skill);
    }

    return $this;
  }

  public function removeSkill(Skill $skill): self
  {
    $this->skills->removeElement($skill);

    return $this;
  }

  public function isIsMain(): ?bool
  {
      return $this->is_main;
  }

  public function setIsMain(bool $is_main): self
  {
      $this->is_main = $is_main;

      return $this;
  }
}

src/Controller/CodeTypeController.php
<?php

namespace App\Controller;

use App\Entity\Code;
use App\Form\CodeType;
use App\Repository\CodeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/backoffice/code/type')]
class CodeTypeController extends AbstractController
{
    #[Route('/', name: 'app_code_type_index', methods: ['GET'])]
    public function index(CodeRepository $codeRepository): Response
    {
        return $this->render('code_type/index.html.twig', [
            'codes' => $codeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_code_type_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CodeRepository $codeRepository): Response
    {
        $code = new Code();
        $form = $this->createForm(CodeType::class, $code);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $codeRepository->save($code, true);

            return $this->redirectToRoute('app_code_type_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('code_type/new.html.twig', [
            'code' => $code,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_code_type_show', methods: ['GET'])]
    public function show(Code $code): Response
    {
        return $this->render('code_type/show.html.twig', [
            'code' => $code,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_code_type_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Code $code, CodeRepository $codeRepository): Response
    {
        $form = $this->createForm(CodeType::class, $code);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $codeRepository->save($code, true);

            return $this->redirectToRoute('app_code_type_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('code_type/edit.html.twig', [
            'code' => $code,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_code_type_delete', methods: ['POST'])]
    public function delete(Request $request, Code $code, CodeRepository $codeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$code->getId(), $request->request->get('_token'))) {
            $codeRepository->remove($code, true);
        }

        return $this->redirectToRoute('app_code_type_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/code_type/_delete_form.html.twig
<form method="post" action="{{ path('app_code_type_delete', {'id': code.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer ce code ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ code.id) }}">
    <button class="btn mt-2"><img src="{{asset('build/img/trash-icon.svg')}}" alt="icon poubelle" title="Supprimer"></button>
</form>

templates/code_type/_form.html.twig
{{ form_start(form) }}
    {% form_theme form 'bootstrap_5_layout.html.twig' %}

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.identifier, "Identifiant :") }}
            {{ form_widget(form.identifier) }}
            {{ form_errors(form.identifier) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.title, "Titre :") }}
            {{ form_widget(form.title) }}
            {{ form_errors(form.title) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.is_main, "Hiérarchie :") }}
            {{ form_widget(form.is_main) }}
            {{ form_errors(form.is_main) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.skills, 'Compétences :') }}
            {{ form_widget(form.skills) }}
            {{ form_errors(form.skills) }}
        </div>   
    </div>

    <div class="row mt-2">
        <div class="col-lg-10 d-flex justify-content-end">
            <button class="btn btn-primary my-3">{{ button_label|default('Sauvegarder') }}</button>
        </div>
    </div>
{{ form_end(form) }}

templates/code_type/edit.html.twig
{% extends 'backoffice_base.html.twig' %}

{% block title %}Code | Éditer{% endblock %}

{% block body %}
    <div class="page" data-current="codes"></div>
    <div class="d-flex justify-content-between mb-5 col-lg-10">
        <div class="d-flex">
            <h1>Éditer un code</h1>
            {{ include('code_type/_delete_form.html.twig') }}
        </div>
        <a class="mt-3" href="{{ path('app_code_type_index') }}"><img src="{{asset('build/img/back-icon.svg')}}" alt="icon back" title="Retour en arrière"></a>
    </div>

    {{ include('code_type/_form.html.twig', {'button_label': 'Modifier'}) }}

    {% block javascripts %}
        {{ encore_entry_script_tags('backoffice') }}
        {{parent()}}
    {% endblock %}
{% endblock %}

templates/code_type/index.html.twig
{% extends 'backoffice_base.html.twig' %}

{% block title %}Codes | Index{% endblock %}

{% block body %}
    <div class="page" data-current="codes"></div>
    <div class="d-flex justify-content-between mb-5">
        <h1>Codes</h1>
        <a href="{{ path('app_code_type_new') }}"><img src="{{asset('build/img/plus-icon.svg')}}" alt="icon plus" title="Ajouter un code"></a>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Identifiant</th>
                <th>Titre</th>
                <th>Hiérarchie</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for code in codes %}
            <tr>
                <td>{{ code.identifier }}</td>
                <td>{{ code.title }}</td>
                <td>
                {% if code.isMain %}
                    Code principal
                {% else %}
                    Code secondaire
                {% endif %}</td>
                <td>
                    <div class="d-flex justify-content-around">
                        <a href="{{ path('app_code_type_show', {'id': code.id}) }}"><img src="{{asset('build/img/show-icon.svg')}}" class="me-2" alt="icon show" title="Voir l'entité"></a>
                        <a href="{{ path('app_code_type_edit', {'id': code.id}) }}"><img src="{{asset('build/img/edit-icon.svg')}}" alt="icon edit" title="Modifier l'entité"></a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% block javascripts %}
        {{ encore_entry_script_tags('backoffice') }}
        {{parent()}}
    {% endblock %}
{% endblock %}

templates/code_type/new.html.twig
{% extends 'backoffice_base.html.twig' %}

{% block title %}Code | Nouveau{% endblock %}

{% block body %}
    <div class="page" data-current="codes"></div>
    <div class="d-flex justify-content-between mb-5 col-lg-10">
        <h1>Créer un nouveau code</h1>
        <a class="mt-3" href="{{ path('app_code_type_index') }}"><img src="{{asset('build/img/back-icon.svg')}}" alt="icon back" title="Retour en arrière"></a>
    </div>

    {{ include('code_type/_form.html.twig') }}

    {% block javascripts %}
        {{ encore_entry_script_tags('backoffice') }}
        {{parent()}}
    {% endblock %}
{% endblock %}

templates/code_type/show.html.twig
{% extends 'backoffice_base.html.twig' %}

{% block title %}Code | Aperçu{% endblock %}

{% block body %}
    <div class="page" data-current="codes"></div>
    <div class="d-flex justify-content-between mb-5 col-lg-10">
        <div class="d-flex">
            <h1>Code | Aperçu</h1>
            {{ include('code_type/_delete_form.html.twig') }}
        </div>
        <div class="d-flex">
            <a class="mt-3" href="{{ path('app_code_type_edit', {'id': code.id}) }}"><img src="{{asset('build/img/edit-icon.svg')}}" alt="icon edit" title="Modifier l'entité"></a>
            <a class="mt-3 ms-3" href="{{ path('app_code_type_index') }}"><img src="{{asset('build/img/back-icon.svg')}}" alt="icon back" title="Retour en arrière"></a>
        </div>
    </div>

    <div class="col-lg-10">
        <table class="table">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ code.id }}</td>
                </tr>
                <tr>
                    <th>Identifiant</th>
                    <td>{{ code.identifier }}</td>
                </tr>
                <tr>
                    <th>Titre</th>
                    <td>{{ code.title }}</td>
                </tr>
                <tr>
                    <th>Hiérarchie</th>
                    <td>
                        {% if code.isMain %}
                            Code principal
                        {% else %}
                            Code secondaire
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th>Compétences</th>
                    <td>
                        {% for skill in code.skills %}
                            {{skill}}<br/>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>Formations liées</th>
                    <td>
                        {% for formation in code.formations %}
                            {{formation}}<br/>
                        {% endfor %}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    {% block javascripts %}
        {{ encore_entry_script_tags('backoffice') }}
        {{parent()}}
    {% endblock %}
{% endblock %}