src/Entity/Location.php
<?php

namespace App\Entity;

use Symfony\Component\Uid\Uuid;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\LocationRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: LocationRepository::class)]
class Location
{
  #[ORM\Id]
  #[ORM\Column(type: UuidType::NAME, unique: true)]
  #[ORM\GeneratedValue(strategy: 'CUSTOM')]
  #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
  private ?Uuid $id = null;

  #[ORM\Column(length: 255)]
  #[Assert\NotBlank]
  #[Assert\Length(
    max: 255,
    maxMessage: 'La ligne 1 ne peut pas contenir plus de 255 caractères.',
  )]
  private ?string $line_1 = null;

  #[ORM\Column(length: 255)]
  #[Assert\NotBlank]
  #[Assert\Length(
    max: 255,
    maxMessage: 'La ligne 2 ne peut pas contenir plus de 255 caractères.',
  )]
  private ?string $line_2 = null;

  #[ORM\Column(length: 255)]
  #[Assert\NotBlank]
  #[Assert\Length(
    max: 255,
    maxMessage: 'La ville ne peut pas contenir plus de 255 caractères.',
  )]
  private ?string $city = null;

  #[ORM\Column]
  #[Assert\NotBlank]
  #[Assert\Length(
    min: 5,
    max: 5,
  )]
  private ?string $zip_code = null;

  #[ORM\ManyToMany(targetEntity: Formation::class, mappedBy: 'locations')]
  private Collection $formations;

  public function __construct()
  {
    $this->formations = new ArrayCollection();
  }

  public function __toString(): string
  {
    return $this->line_1;
  }

  public function getId(): ?Uuid
  {
    return $this->id;
  }

  public function getLine1(): ?string
  {
    return $this->line_1;
  }

  public function setLine1(string $line_1): self
  {
    $this->line_1 = $line_1;

    return $this;
  }

  public function getLine2(): ?string
  {
    return $this->line_2;
  }

  public function setLine2(string $line_2): self
  {
    $this->line_2 = $line_2;

    return $this;
  }

  public function getCity(): ?string
  {
    return $this->city;
  }

  public function setCity(string $city): self
  {
    $this->city = $city;

    return $this;
  }

  public function getZipCode(): ?string
  {
    return $this->zip_code;
  }

  public function setZipCode(string $zip_code): self
  {
    $this->zip_code = $zip_code;

    return $this;
  }

  /**
   * @return Collection<int, Formation>
   */
  public function getFormations(): Collection
  {
    return $this->formations;
  }

  public function addFormation(Formation $formation): self
  {
    if (!$this->formations->contains($formation))
    {
      $this->formations->add($formation);
      $formation->addLocation($this);
    }

    return $this;
  }

  public function removeFormation(Formation $formation): self
  {
    if ($this->formations->removeElement($formation))
    {
      $formation->removeLocation($this);
    }

    return $this;
  }
}

src/Controller/LocationTypeController.php
<?php

namespace App\Controller;

use App\Entity\Location;
use App\Form\LocationType;
use App\Repository\LocationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/backoffice/location/type')]
class LocationTypeController extends AbstractController
{
    #[Route('/', name: 'app_location_type_index', methods: ['GET'])]
    public function index(LocationRepository $locationRepository): Response
    {
        return $this->render('location_type/index.html.twig', [
            'locations' => $locationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_location_type_new', methods: ['GET', 'POST'])]
    public function new(Request $request, LocationRepository $locationRepository): Response
    {
        $location = new Location();
        $form = $this->createForm(LocationType::class, $location);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $locationRepository->save($location, true);

            return $this->redirectToRoute('app_location_type_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('location_type/new.html.twig', [
            'location' => $location,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_location_type_show', methods: ['GET'])]
    public function show(Location $location): Response
    {
        return $this->render('location_type/show.html.twig', [
            'location' => $location,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_location_type_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Location $location, LocationRepository $locationRepository): Response
    {
        $form = $this->createForm(LocationType::class, $location);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $locationRepository->save($location, true);

            return $this->redirectToRoute('app_location_type_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('location_type/edit.html.twig', [
            'location' => $location,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_location_type_delete', methods: ['POST'])]
    public function delete(Request $request, Location $location, LocationRepository $locationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$location->getId(), $request->request->get('_token'))) {
            $locationRepository->remove($location, true);
        }

        return $this->redirectToRoute('app_location_type_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/location_type/_delete_form.html.twig
<form method="post" action="{{ path('app_location_type_delete', {'id': location.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer ce lieu ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ location.id) }}">
    <button class="btn mt-2"><img src="{{asset('build/img/trash-icon.svg')}}" alt="icon poubelle" title="Supprimer"></button>
</form>

templates/location_type/_form.html.twig
{{ form_start(form) }}
    {% form_theme form 'bootstrap_5_layout.html.twig' %}

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.line_1, "Ligne 1 :") }}
            {{ form_widget(form.line_1) }}
            {{ form_errors(form.line_1) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.line_2, "Ligne 2 :") }}
            {{ form_widget(form.line_2) }}
            {{ form_errors(form.line_2) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.city, 'Ville :') }}
            {{ form_widget(form.city) }}
            {{ form_errors(form.city) }}
        </div>   
    </div>

    <div class="row mt-4">
        <div class="col-lg-10">
            {{ form_label(form.zip_code, 'Codes :') }}
            {{ form_widget(form.zip_code) }}
            {{ form_errors(form.zip_code) }}
        </div>   
    </div>

    <div class="row mt-2">
        <div class="col-lg-10 d-flex justify-content-end">
            <button class="btn btn-primary my-3">{{ button_label|default('Sauvegarder') }}</button>
        </div>
    </div>
{{ form_end(form) }}

templates/location_type/edit.html.twig
{% extends 'backoffice_base.html.twig' %}

{% block title %}Lieu | Éditer{% endblock %}

{% block body %}
    <div class="page" data-current="lieux"></div>
    <div class="d-flex justify-content-between mb-5 col-lg-10">
        <div class="d-flex">
            <h1>Éditer un lieu</h1>
            {{ include('location_type/_delete_form.html.twig') }}
        </div>
        <a class="mt-3" href="{{ path('app_location_type_index') }}"><img src="{{asset('build/img/back-icon.svg')}}" alt="icon back" title="Retour en arrière"></a>
    </div>

    {{ include('location_type/_form.html.twig', {'button_label': 'Modifier'}) }}

    {% block javascripts %}
        {{ encore_entry_script_tags('backoffice') }}
        {{parent()}}
    {% endblock %}
{% endblock %}

templates/location_type/index.html.twig
{% extends 'backoffice_base.html.twig' %}

{% block title %}Lieux | Index{% endblock %}

{% block body %}
    <div class="page" data-current="lieux"></div>
    <div class="d-flex justify-content-between mb-5">
        <h1>Lieux</h1>
        <a href="{{ path('app_location_type_new') }}"><img src="{{asset('build/img/plus-icon.svg')}}" alt="icon plus" title="Ajouter un lieu"></a>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Ville</th>
                <th>Ligne 1</th>
                <th>Ligne 2</th>
                <th>Code postal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for location in locations %}
            <tr>
                <td>{{ location.city }}</td>
                <td>{{ location.line1 }}</td>
                <td>{{ location.line2 }}</td>
                <td>{{ location.zipCode }}</td>
                <td>
                    <div class="d-flex justify-content-around">
                        <a href="{{ path('app_location_type_show', {'id': location.id}) }}"><img src="{{asset('build/img/show-icon.svg')}}" class="me-2" alt="icon show" title="Voir l'entité"></a>
                        <a href="{{ path('app_location_type_edit', {'id': location.id}) }}"><img src="{{asset('build/img/edit-icon.svg')}}" alt="icon edit" title="Modifier l'entité"></a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% block javascripts %}
        {{ encore_entry_script_tags('backoffice') }}
        {{parent()}}
    {% endblock %}
{% endblock %}

templates/location_type/new.html.twig
{% extends 'backoffice_base.html.twig' %}

{% block title %}Lieu | Nouveau{% endblock %}

{% block body %}
    <div class="page" data-current="lieux"></div>
    <div class="d-flex justify-content-between mb-5 col-lg-10">
        <h1>Créer un nouveau lieu</h1>
        <a class="mt-3" href="{{ path('app_location_type_index') }}"><img src="{{asset('build/img/back-icon.svg')}}" alt="icon back" title="Retour en arrière"></a>
    </div>

    {{ include('location_type/_form.html.twig') }}

    {% block javascripts %}
        {{ encore_entry_script_tags('backoffice') }}
        {{parent()}}
    {% endblock %}
{% endblock %}

templates/location_type/show.html.twig
{% extends 'backoffice_base.html.twig' %}

{% block title %}Lieu | Aperçu{% endblock %}

{% block body %}
    <div class="page" data-current="lieux"></div>
    <div class="d-flex justify-content-between mb-5 col-lg-10">
        <div class="d-flex">
            <h1>Lieu</h1>
            {{ include('location_type/_delete_form.html.twig') }}
        </div>
        <div class="d-flex">
            <a class="mt-3" href="{{ path('app_location_type_edit', {'id': location.id}) }}"><img src="{{asset('build/img/edit-icon.svg')}}" alt="icon edit" title="Modifier l'entité"></a>
            <a class="mt-3 ms-3" href="{{ path('app_location_type_index') }}"><img src="{{asset('build/img/back-icon.svg')}}" alt="icon back" title="Retour en arrière"></a>
        </div>
    </div>

    <div class="col-lg-10">
        <table class="table">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ location.id }}</td>
                </tr>
                <tr>
                    <th>Ville</th>
                    <td>{{ location.city }}</td>
                </tr>
                <tr>
                    <th>Ligne 1</th>
                    <td>{{ location.line1 }}</td>
                </tr>
                <tr>
                    <th>Ligne 2</th>
                    <td>{{ location.line2 }}</td>
                </tr>
                <tr>
                    <th>Code postal</th>
                    <td>{{ location.zipCode }}</td>
                </tr>
                <tr>
                    <th>Formations liées</th>
                    <td>
                        {% for formation in location.formations %}
                            {{formation}}<br/>
                        {% endfor %}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    {% block javascripts %}
        {{ encore_entry_script_tags('backoffice') }}
        {{parent()}}
    {% endblock %}
{% endblock %}